[tool.poetry]
name = "firstflask"
version = "0.1.0"
description = ""
authors = ["12"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
